# -------------------------
# APP
# -------------------------
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# -------------------------
# METRICS
# -------------------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      status:
        http-mapping:
          down: 500
      show-details: always
  httpexchanges:
    recording:
      include: request-headers,time-taken,session-id

# -------------------------
# SPRING CLOUD
# -------------------------
spring:
  application:
    name: bff-svc
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        # ------------------------------------------------
        # ROUTE FOR GENERATE A CAPTCHA CODE.
        # ------------------------------------------------
        - id: captcha-generate
          uri: http://captcha.transversales.svc.cluster.local:8080
          predicates:
            - Path=/telefonica/resource/v1/captcha/generate

        # ------------------------------------------------
        # ROUTE TEST SERVICE MOCK DATA.
        # ------------------------------------------------
        - id: jsonplaceholder-test
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/**

# ------------------
# CUSTOM HEADER
# ------------------
allowed:
  origin: https://datos-contacto-desa.telefonicawebsites.co
